services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clubpoisson
      POSTGRES_USER: clubpoisson
      POSTGRES_PASSWORD: clubpoisson
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clubpoisson"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  backend:
    image: ghcr.io/yassineinnovator/backend:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      PGHOST: postgres
      PGDATABASE: clubpoisson
      PGUSER: clubpoisson
      PGPASSWORD: clubpoisson
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8081:80" # <--- J'ai mis 8081 ici pour éviter le conflit !
    depends_on:
      - backend

volumes:
  pgdata:
