services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clubpoisson
      POSTGRES_USER: clubpoisson
      POSTGRES_PASSWORD: clubpoisson
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clubpoisson"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  backend:
    # Image qui sera construite par GitHub Actions
    image: ghcr.io/yassineinnovator/teaching-fish-keepers-backend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGHOST: postgres
      PGDATABASE: clubpoisson
      PGUSER: clubpoisson
      PGPASSWORD: clubpoisson
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    # Image qui sera construite par GitHub Actions
    image: ghcr.io/yassineinnovator/teaching-fish-keepers-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: